# railway.toml

[project]
name = "projetoVendas"

[build]
# se você usa Dockerfile, deixe vazio ou aponte pra ele


[deploy]
preDeployCommand = "npm run migrate && npm run seed"
startCommand     = "npm start"


