[project]
name = "projetoVendas"

[build]
# (vazio ou seu Dockerfile, se houver)

[deploy]
# Antes do start, cria tabelas e popula o admin
preDeployCommand = "npm run migrate && npm run seed"
startCommand     = "npm start"

