[build]
buildCommand = ""      # vazio porque o Dockerfile jรก faz o npm ci

[deploy]
preDeployCommand = "npm run migrate && npm run seed"
startCommand    = "npm start"
restartPolicyType = "ON_FAILURE"
